title        = "The Reactive Foundation"
baseURL      = "https://reactive.foundation"
languageCode = "en-us"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
font_awesome_version = "5.3.1"
description = "An open source software foundation dedicated to promoting the usage of reactive programming and systems in production."
copyright = "All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our [Trademark Usage](https://www.linuxfoundation.org/trademark-usage) page. Linux is a registered trademark of Linus Torvalds. [Privacy Policy](http://www.linuxfoundation.org/privacy) and [Terms of Use](http://www.linuxfoundation.org/terms). "
github_repo = "https://github.com/reactivefoundation"

[params.logos]
navbar = "reactivefoundation-horizontal-white.png"
hero   = "reactivefoundation-stacked-color.png"
footer = "reactivefoundation-stacked-white.png"

[[params.info.columns]]
title = "What are Reactive Systems?"
content = "Building modern, cloud native applications often require reactive systems that are responsive, resilient, elastic and message driven. The Reactive Foundation offers a neutral ecosystem of support for open source projects enabling developers building reactive applications on cloud native infrastructure. Reactive Systems is set of principles promoting responsive, resilient, elastic, message-driven design patterns."

[[params.info.columns]]
title = "What is Reactive Programming?"
content = """
Reactive programming is a subset of asynchronous programming and a paradigm where the availability of new information drives the logic forward rather than having control flow driven by a thread-of-execution. Reactive programming is thus a declarative programming paradigm for data streams and the propagation of change, and simplifies the creation of interactive user interfaces and near-real-time system interaction.
"""

[[menu.main]]
name = "About"
url = "/about"
weight = 1

[[menu.main]]
name = "News"
identifier = "news"
weight = 2

[[menu.main]]
name = "Members"
identifier = "members"
weight = 3

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 4

[[menu.main]]
name = "All News"
url = "/news"
parent = "news"

[[menu.main]]
name = "Announcements"
url = "/news/announcements"
parent = "news"

[[menu.main]]
name = "In the News"
url = "/news/in-the-news"
parent = "news"

[[menu.main]]
name = "Current members"
url = "/members"
parent = "members"

[[menu.main]]
name = "Join"
url = "/join"
parent = "members"

# Reactive Foundation members
[[params.members]]
img = "alibaba.svg"
url = "https://www.alibabagroup.com"

[[params.members]]
img = "facebook.svg"
url = "https://facebook.com"

[[params.members]]
img = "lightbend.svg"
url = "https://lightbend.com"

[[params.members]]
img = "netifi.svg"
url = "https://www.netifi.com"

[[params.members]]
img = "vlingo.svg"
url = "https://vlingo.io"

[[params.members]]
img = "vmware.jpg"
url = "https://www.vmware.com/company.html"

# Reactive Foundation projects
[[params.projects]]
name = "RSocket"
url = "http://rsocket.io"
img = "rsocket.svg"
description = "A binary protocol for use on byte stream transports such as TCP, WebSockets, and Aeron."

[permalinks]
news = "/news/:year/:month/:day/:title"
