title        = "The Reactive Foundation"
languageCode = "en-us"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
font_awesome_version = "5.3.1"
description = "A foundation supporting reactive programming"
copyright = "All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our [Trademark Usage](https://www.linuxfoundation.org/trademark-usage) page. Linux is a registered trademark of Linus Torvalds. [Privacy Policy](http://www.linuxfoundation.org/privacy) and [Terms of Use](http://www.linuxfoundation.org/terms). "
github_repo = "https://github.com/reactivefoundation"

[params.logos]
navbar = "reactivefoundation-horizontal-white.png"
hero   = "reactivefoundation-stacked-color.png"
footer = "reactivefoundation-stacked-white.png"

[[params.info.columns]]
title = "What is the Reactive Foundation?"
content = "Placeholder"

[[params.info.columns]]
title = "What is Reactive Programming?"
content = "Placeholder"

[params.explanation]
columns = [
"""
Placeholder.
""",
"""
Placeholder.
"""
]

[[menu.navbar]]
name = "About"
url = "/about"
weight = 1

[[menu.navbar]]
name = "Projects"
url = "/projects"
weight = 2
