title        = "The Reactive Foundation"
baseURL      = "https://reactive.foundation"
languageCode = "en-us"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
font_awesome_version = "5.3.1"
description = "A foundation supporting reactive programming"
copyright = "All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our [Trademark Usage](https://www.linuxfoundation.org/trademark-usage) page. Linux is a registered trademark of Linus Torvalds. [Privacy Policy](http://www.linuxfoundation.org/privacy) and [Terms of Use](http://www.linuxfoundation.org/terms). "
github_repo = "https://github.com/reactivefoundation"

[params.logos]
navbar = "reactivefoundation-horizontal-white.png"
hero   = "reactivefoundation-stacked-color.png"
footer = "reactivefoundation-stacked-white.png"

[[params.info.columns]]
title = "What is the Reactive Foundation?"
content = "An open source software foundation dedicated to promoting the usage of reactive programming in production."

[[params.info.columns]]
title = "What is Reactive Programming?"
content = """
A set of principles promoting responsive, resilient, elastic, message-driven design patterns. For more info, see the [Reactive Manifesto](https://www.reactivemanifesto.org/).
"""

[params.explanation]
columns = [
"""
Building modern, cloud native applications often require reactive systems that are responsive, resilient, elastic and message driven. The Reactive Foundation offers a neutral ecosystem of support for open source projects enabling developers building reactive applications on cloud native infrastructure.
""",
"""
Reactive programming is a declarative programming paradigm for data streams and the propagation of change, and simplifies the creation of interactive user interfaces and near-real-time system animation. .
"""
]

[[menu.navbar]]
name = "About"
url = "/about"
weight = 1

[[menu.navbar]]
name = "Projects"
url = "/projects"
weight = 2
