title        = "The Reactive Foundation"
languageCode = "en-us"

[params]
description = "A foundation supporting reactive programming"

[params.logos]
navbar = "reactivefoundation-horizontal-white.png"
hero   = "reactivefoundation-stacked-color.png"
footer = "reactivefoundation-stacked-white.png"

[[params.info.columns]]
title = "What is the Reactive Foundation?"
content = "Placeholder"

[[params.info.columns]]
title = "What is Reactive Programming?"
content = "Placeholder"

[params.explanation]
columns = [
"""
Placeholder.
""",
"""
Placeholder.
"""
]

[[menu.navbar]]
name = "About"
url = "/about"
weight = 1

[[menu.navbar]]
name = "Projects"
url = "/projects"
weight = 2
